Add Ticket Availability and Logo entities
Marat555/eventbrite-api-laravel-wrapper pull request #21
Opened 2020-02-14 04:50 UTC by jmurphy45

Add additional functionality to the wrapper for the most recent api.

2020-02-15 18:26 UTC, jmurphy45 commented
Fixed Address bug on needs to be address_1

2020-02-16 15:56 UTC, Marat555 commented
Hi, @jmurphy45. I'll check up your pull request today or tomorrow.

2020-02-20 12:45 UTC, bigdevwhale requested changes

2020-02-20 12:45 UTC, Marat555 commented on src/Factories/Entity/TicketAvailability.php
> +//{"has_available_tickets":true,"minimum_ticket_price":{"currency":"USD","value":2000,"major_value":"20.00","display":"20.00 USD"},"maximum_ticket_price":{"currency":"USD","value":2000,"major_value":
pls remove comments

2020-02-20 12:45 UTC, Marat555 commented on src/Factories/Entity/TicketAvailability.php
> + */
pls remove autogenerated comments

2020-02-20 12:45 UTC, Marat555 commented on src/Factories/Entity/Logo.php
> + */
pls remove autogenerated comments

2020-02-20 12:45 UTC, Marat555 commented on src/Factories/Entity/TicketAvailability.php
> +    public $startSalesDate;
fix code style pls and add comments
Example:
`class CropMask extends AbstractEntity
{

    /**
     * The upload_token from the GET portion of the upload
     *
     * @var string
     */
    public $uploadToken;

    /**
     * Coordinate for top-left corner of crop mask
     *
     * @var TopLeft
     */
    public $topLeft;

    /**
     * Crop mask width
     *
     * @var number
     */
    public $width;

    /**
     * Crop mask height
     *
     * @var number
     */
    public $height;
}`

2020-02-23 16:18 UTC, bigdevwhale requested changes

2020-02-23 16:18 UTC, Marat555 commented on src/Factories/Client.php
> +use Illuminate\Support\Facades\Log;
pls delete this namespace because Log class is not needed here

2020-02-23 16:18 UTC, Marat555 commented on src/Factories/Api/AbstractApi.php
> +use Illuminate\Support\Facades\Log;
pls delete this namespace because Log class is not needed here

2020-02-23 16:18 UTC, Marat555 commented on src/Eventbrite.php
> +use Illuminate\Support\Facades\Log;
pls delete this namespace because Log class is not needed here

2020-02-23 16:18 UTC, Marat555 commented on src/Factories/Entity/AbstractEntity.php
> +//        Log::info($property);
pls delete debug code

2020-02-23 16:18 UTC, Marat555 commented on src/Factories/Entity/AbstractEntity.php
> +use Illuminate\Support\Facades\Log;
pls delete this namespace because Log class is not needed here

2020-02-26 19:45 UTC, merged